/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/loading-screen/loading-screen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/transaction/tx.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/transaction-grid/tx-grid.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/tx-date-block/tx-date-block.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/header/header.styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/loading-screen/loading-screen.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/index.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/transaction/tx.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/transaction-grid/tx-grid.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/tx-date-block/tx-date-block.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/header/header.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/loading-screen/loading-screen.styles${`?${string}` | `#${string}` | ''}` | `/index.styles${`?${string}` | `#${string}` | ''}` | `/../components/transaction/tx.styles${`?${string}` | `#${string}` | ''}` | `/../components/transaction-grid/tx-grid.styles${`?${string}` | `#${string}` | ''}` | `/../components/tx-date-block/tx-date-block.styles${`?${string}` | `#${string}` | ''}` | `/../components/header/header.styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/loading-screen/loading-screen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/transaction/tx.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/transaction-grid/tx-grid.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/tx-date-block/tx-date-block.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/header/header.styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
